### ISSUE TITLE
multi gpu training?

### ISSUE THREAD

**Issue by icoz69** [xiaomi-automl/FairDARTS#3]
Hi, thank you for the nice work. Does this project support multi-gpu training?  How can I modify it to support multiple gpus. Thanks.

**Comment by tianbaochou** [comment]
> Hi, thank you for the nice work. Does this project support multi-gpu training? How can I modify it to support multiple gpus. Thanks.

Indeed, We support mult-gpus for training. 
For example: 
**If you prefer to run in gpu:0,1 and 2, the bash script below maybe what you want**
>CUDA_VISIBLE_DEVICES=0,1,2 python train.py --auxiliary --cutout --arch FairDARTS_a --parse_method threshold --batch_size 196 --epoch 600 --multi-gpus

However, the performance sometimes maybe not better even worse than single GPU when you evaluate on CIFAR-10 dataset. Because more GPUs the batch size in single GPU is less.

**Comment by icoz69** [comment]
@tianbaochou  Thank you for your reply. By the way, I just go through your code and found that the optimization of architecture parameter and network parameter are conducted alternatively by SGD, and there is no second-order gradient. Is it right? But in DARTS, there is some analysis on that bi-level optimization. So, why not try the high-order gradient?

**Comment by tianbaochou** [comment]
> level

+ Because second-order gradient is GPU-Memory cost it need much more GPU than first-order. In FairDARTS, we have done many experiments and a fast search cost is prefered (Batch size = 128 the search gpu memory cost about 20G even in first order).

+ Second-order do not have significant improvement in previous related DARTS works.

**Comment by tianbaochou** [comment]
> @tianbaochou Thank you for your reply. By the way, I just go through your code and found that the optimization of architecture parameter and network parameter are conducted alternatively by SGD, and there is no second-order gradient. Is it right? But in DARTS, there is some analysis on that bi-level optimization. So, why not try the high-order gradient?

+ Because second-order gradient is GPU-Memory cost it need much more GPU than first-order. In FairDARTS, we have done many experiments and a fast search cost is prefered (Batch size = 128 the search gpu memory cost about 20G even in first order).

+ Second-order do not have significant improvement in previous related DARTS works.

**Comment by icoz69** [comment]
@tianbaochou thank you for your kind explanations!

**Comment by icoz69** [comment]
btw, whats the difference between train_search.py and train.py . it seems no multi_gpu option in train_search.py

**Comment by tianbaochou** [comment]
> btw, whats the difference between train_search.py and train.py . it seems no multi_gpu option in train_search.py

Train_Search is searching phase and train is evaluation phase (train the architecture model searched from scratch). We keep the structure from DARTS. search phase not support multi-gpus, but easily to implemnt. see **pt.darts**.  In our experiments, it's not need to search in multi-gpus.
