### ISSUE TITLE
Feature request: adding functionality to specify input shape of data in one place

### ISSUE THREAD

**Issue by christofer-f** [xiaomi-automl/FairDARTS#4]
Hi again...

I have tried to modify the code to fit the MNIST dataset but I run into trouble.
It seems that one needs to modify the input shape of the data in several places to get it to work.

Is it possible to refactor the code and define the first layer in a more general way?
Or could you give me instructions on where the code needs to be changed to fit other datasets?

//Christofer

**Comment by tianbaochou** [comment]
> Hi again...
> 
> I have tried to modify the code to fit the MNIST dataset but I run into trouble.
> It seems that one needs to modify the input shape of the data in several places to get it to work.
> 
> Is it possible to refactor the code and define the first layer in a more general way?
> Or could you give me instructions on where the code needs to be changed to fit other datasets?
> 
> //Christofer

Thanks you for insteresting. 

+ For searching, AuxiliaryHeadCIFAR and Network  in 'model_search.py'  should change the input image channels from 3 to 1.

+ For training,  AuxiliaryHeadCIFAR and NetworkCIFAR in 'model.py' should change the input image channels from 3 to 1. 

+ DataAugmentation, such mean, std also need to be correctly changed.

MNIST dataset is no consider within most of current NAS work. since it is easy to overfit and does not a good proxy dataset for evaluating the search algorithm godd or not.

**Comment by christofer-f** [comment]
I have got the code running with the MNIST dataset. Thanks for all help!

I have some experiments that I would like to perform. 
For example to apply NAS on the "spiral case" in https://playground.tensorflow.org/ 
But in order to do that, I need to create a minimal version of this project.
